(*————————————————————————————————————————————————————————————————————————————
   Copyright (c) 2020–2021 Craig Ferguson <me@craigfe.io>
   Distributed under the MIT license. See terms at the end of this file.
  ————————————————————————————————————————————————————————————————————————————*)

module type Style = sig
  type color

  type t
  (** The type of terminal {i styles}: values that can be printed to a terminal
      in order to change the way that it renders text. *)

  val code : t -> string
  (** Get the ANSI escape code for the given style. *)

  (** Constructing ANSI styles: *)

  val none : t
  val bold : t
  val faint : t
  val italic : t
  val underline : t
  val reverse : t
  val fg : color -> t
  val bg : color -> t
end

module type Ansi = sig
  module Color : sig
    type t
    (** The type of colours that can be rendered to a terminal. See {!Ansi} for
        functions that render these colours to *)

    (** {2 Standard ANSI escape sequences} *)

    type plain =
      [ `black | `blue | `cyan | `green | `magenta | `red | `white | `yellow ]

    val of_ansi : [ plain | `bright of plain ] -> t

    (** {2 24-bit RGB colours}

        Most modern terminals support true colour, but it is still not as
        portable as the plain ANSI escape sequences generated by {!of_ansi}. *)

    val of_rgb : int -> int -> int -> t
    val of_hex : string -> t

    (* val pp_dump : t Fmt.t *)
    (** Pretty-print the internal structure of *)
  end

  module type Style = Style

  module Style : Style with type color := Color.t

  val show_cursor : string
  val hide_cursor : string
  val move_up : int Fmt.t
  val move_down : int Fmt.t
  val erase_line : string
  val erase_display_suffix : string
end

(*————————————————————————————————————————————————————————————————————————————
   Copyright (c) 2020–2021 Craig Ferguson <me@craigfe.io>

   Permission to use, copy, modify, and/or distribute this software for any
   purpose with or without fee is hereby granted, provided that the above
   copyright notice and this permission notice appear in all copies.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
  ————————————————————————————————————————————————————————————————————————————*)
